INSERT INTO job (position),
    VALUES ('unknown'),
      ('Pitcher'),
      ('Catcher'),
      ('First Base'),
      ('Second Base'),
      ('Third Base'),
      ('Shortstop'),
      ('Left Field'),
      ('Center Field'),
      ('Right Field');